### PR TITLE
operators: Fix location of enriched fields

### LINKED ISSUE #3459: UidGidResolver does not act on inner fields
## Description

Fields of type `gadget_uid` and `gadget_gid` can be enriched by the `UidGidResolver` operator when it is directly part of the `struct event`:
```c
gadget_uid uid;
```

However, it does not work when it is part of another struct:
```c
struct process {
	__u32 ppid;
	__u32 pid;
	__u32 tid;
	char comm[TASK_COMM_LEN];
	char pcomm[TASK_COMM_LEN];
	gadget_uid uid;
	gadget_uid gid;
};
struct gadget_event {
	gadget_timestamp timestamp_raw;
	struct process tracee;
	struct process tracer;
...
};
```

See discussion https://github.com/inspektor-gadget/inspektor-gadget/pull/3438#discussion_r1741781314

## Impact

For now, the structs have to stay flat.

## Expected behavior

The `UidGidResolver` operator can act on inner fields

## Additional information

https://github.com/inspektor-gadget/inspektor-gadget/compare/michael/datasources/withsameparent

### PR DESCRIPTION
**Pull request by mauriciovasquezbernal**
Before this commit operators were creating the enriched field in the root of the data source. This commit fixes that by creating the enriched fields in the same node of the "raw" one.

### Testing 

I used the following gadget to test it:

```c
#include <vmlinux.h>
#include <bpf/bpf_helpers.h>
#include <gadget/buffer.h>
#include <gadget/macros.h>
#include <gadget/types.h>

enum myenum {
	ONE = 1,
	TWO = 2,
	THREE = 3,
};

// Just to show inner fields
struct inner {
	gadget_uid inner_user_raw;
	gadget_gid inner_group_raw;
	gadget_syscall inner_syscall_raw;
	gadget_errno inner_errno_raw;
	enum myenum inner_enum_raw;
};

struct event {
	__u32 pid;

	gadget_uid user_raw;
	gadget_gid group_raw;
	gadget_syscall syscall_raw;
	gadget_errno errno_raw;
	enum myenum enum_raw;

	struct inner inner;
};

GADGET_TRACER_MAP(open_events, 1024 * 256);
GADGET_TRACER(open, open_events, event);

SEC("tracepoint/syscalls/sys_enter_openat")
int enter_openat(struct trace_event_raw_sys_enter *ctx)
{
	struct event *event;

	event = gadget_reserve_buf(&open_events, sizeof(*event));
	if (!event)
		return 0;

	u64 uid_gid = bpf_get_current_uid_gid();

	event->pid = bpf_get_current_pid_tgid() >> 32;

	event->user_raw = (u32)uid_gid;
	event->group_raw = (u32)(uid_gid >> 32);
	event->syscall_raw = 50; // any number just for testing
	event->errno_raw = 15;
	event->enum_raw = TWO;

	event->inner.inner_user_raw = event->user_raw;
	event->inner.inner_group_raw = event->group_raw;
	event->inner.inner_syscall_raw = event->syscall_raw;
	event->inner.inner_errno_raw = event->errno_raw;
	event->inner.inner_enum_raw = event->enum_raw;

	gadget_submit_buf(ctx, &open_events, event, sizeof(*event));

	return 0;
}

char LICENSE[] SEC("license") = "GPL";
```

#### Before 

Note: It's possible that you need to avoid running the command multiple types until it works because of the race condition fixed by the first commit of this PR 

```json
{
  "enum": "TWO",
  "enum_raw": 2,
  "errno": "ENOTBLK",
  "errno_raw": 15,
  "group": "systemd-oom",
  "group_raw": 117,
  "inner": {
    "inner_enum_raw": 2,
    "inner_errno_raw": 15,
    "inner_group_raw": 117,
    "inner_syscall_raw": 50,
    "inner_user_raw": 108
  },
  "inner_errno": "ENOTBLK",
  "inner_group": "systemd-oom",
  "inner_syscall": "SYS_LISTEN",
  "inner_user": "systemd-oom",
  "pid": 1182,
  "syscall": "SYS_LISTEN",
  "syscall_raw": 50,
  "user": "systemd-oom",
  "user_raw": 108
}
```

Notice hwo the enriched inner... fields are wrongly added to the root node .

### after 

```json
{
  "enum": "TWO",
  "enum_raw": 2,
  "errno": "ENOTBLK",
  "errno_raw": 15,
  "group": "systemd-oom",
  "group_raw": 117,
  "inner": {
    "inner_enum": "TWO",
    "inner_enum_raw": 2,
    "inner_errno": "ENOTBLK",
    "inner_errno_raw": 15,
    "inner_group": "systemd-oom",
    "inner_group_raw": 117,
    "inner_syscall": "SYS_LISTEN",
    "inner_syscall_raw": 50,
    "inner_user": "systemd-oom",
    "inner_user_raw": 108
  },
  "pid": 1182,
  "syscall": "SYS_LISTEN",
  "syscall_raw": 50,
  "user": "systemd-oom",
  "user_raw": 108
}
```

Fields are now added to the correct node

Fixes #3459

## TODO

Issues to discuss later on

- [ ] We need a `Close()` method on the operator interface to clean up resources allocated in PreStart()
- [ ] We need to test the formatters (or extend them for this case). Perhaps the gadget I provided here can be the base for a new integration test?
- [ ] Perhaps it makes sense to define a root node for all objects and make Parent() return it instead of nil.

### CODE REVIEW

**Comment by flyth** [comment]
I think this looks good already!

> Perhaps it makes sense to define a root node for all objects and make Parent() return it instead of nil.

Yeah, I think that'd be good. It feels a bit weird that there's a difference in handling.

I thought [this](https://github.com/inspektor-gadget/inspektor-gadget/compare/main...michael/datasources/withsameparent) had made it already into main, appears it didn't 😄  (it's an alternative to a new dedicated function to add fields). I'm fine either way, however.

**Comment by mauriciovasquezbernal** [comment]
> I thought [this](https://github.com/inspektor-gadget/inspektor-gadget/compare/main...michael/datasources/withsameparent) had made it already into main, appears it didn't 😄 (it's an alternative to a new dedicated function to add fields). I'm fine either way, however.

That helps a lot. I used it, thanks!

**Review by flyth — APPROVED** [review]
LGTM from code inspection, will do some manual tests later on.

**Comment by mauriciovasquezbernal** [comment]
I'm merging this now. I'll probably explore implementing a unit test once we have merged #3502.

**Pull request merged**
