### PR TITLE
Add figure depicting all gadgets to README

### PR DESCRIPTION
**Pull request by eiffel-fl**
Hi.

This PR moves the existing figure from `architecture.md` to `README.md`.

Best regards.

### CODE REVIEW

**Comment by flyth** [comment]
This is probably a darkmode-only thing, but for me, the outter text of the svg is barely readable, because it has a transparent/no background:

transparent background in svg

**Comment by burak-ok** [comment]
I think this transparency topic is always there :D
For me it looks like Michaels screenshot. But then when i want to use the figure in a non white background presentation i dislike that it has a default background.

But with `svg` one can easily remove the background when needed for other stuff. And many ppl use dark themes or plugins

**Comment by burak-ok** [comment]
> > For me it looks like Michaels screenshot. But then when i want to use the figure in a non white background presentation i dislike that it has a default background.
> 
> `Ctrl+F5` on the README page when on my branch should do the trick!

Yep. refreshed. Looks "good" now. (Now there is a white rectangle in my all black webpage. Whatever good means :P)
I think i had the page open when you updated your branch :sweat_smile:

**Comment by blixtra** [comment]
LGTM. But as a warning I'm working on some new messaging based on the new functionality that has been added that will likely have this moving again fairly soon.

**Review by mauriciovasquezbernal — APPROVED** [review]
LGTM. Let's merge it even if this could be changed soon.

**Pull request merged**
