### PR TITLE
Adds support for multi containers pod for seccomp-profile.

### LINKED ISSUE #215: [RFE] Merge seccomp profiles for pods with several containers
## Current situation

With the seccomp gadget (#208), users can specify a container and generate a seccomp policy based on the syscalls used by the container. But only one container can be selected at a time.

## Impact

Users cannot easily generate a seccomp policy for pods containing several containers: they would have to generate a seccomp policy for each container individually, and merge the seccomp policies manually.

## Ideal future situation

Ideally, users can select a pod and the gadget would automatically merge the seccomp policies of each individual container into one seccomp policy for the pod.

### PR DESCRIPTION
**Pull request by eiffel-fl**
Hi.

With this PR, I enabled `seccomp-profile` to work on pods with several containers inside.
The idea is to generate a seccomp profile which contains the union of all syscalls used by containers within this pod.
The union works like this:
Container X: [syscallA] = 0, [syscallB] = 1, [syscallC] = 0, [syscallD] = 0
Container Y: [syscallA] = 1, [syscallB] = 0, [syscallC] = 1, [syscallD] = 0
Union:          [syscallA] = 1, [syscallB] = 1, [syscallC] = 1, [syscallD] = 0

I check the above behavior running a pod with two containers (nginx and mariadb) and running them separately in dedicated pods:

```bash
# test contains two containers
francis@pwmachine:~/Codes/kinvolk/inspektor-gadget$ ./kubectl-gadget advise seccomp-profile start -p test        
YgbVs4UQgmpUk0ar
francis@pwmachine:~/Codes/kinvolk/inspektor-gadget$ ./kubectl-gadget advise seccomp-profile stop YgbVs4UQgmpUk0ar
{
  "defaultAction": "SCMP_ACT_ERRNO",
  "architectures": [
    "SCMP_ARCH_X86_64",
    "SCMP_ARCH_X86",
    "SCMP_ARCH_X32"
  ],
  "syscalls": [
    {
      "names": [
        "futex"
      ],
      "action": "SCMP_ACT_ALLOW"
    }
  ]
}
francis@pwmachine:~/Codes/kinvolk/inspektor-gadget$ ./kubectl-gadget advise seccomp-profile start -p nginx       
aSoqfaTyjoCF3XX1
francis@pwmachine:~/Codes/kinvolk/inspektor-gadget$ ./kubectl-gadget advise seccomp-profile stop aSoqfaTyjoCF3XX1
{
  "defaultAction": "SCMP_ACT_ERRNO",
  "architectures": [
    "SCMP_ARCH_X86_64",
    "SCMP_ARCH_X86",
    "SCMP_ARCH_X32"
  ],
  "syscalls": [
    {
      "names": [],
      "action": "SCMP_ACT_ALLOW"
    }
  ]
}
francis@pwmachine:~/Codes/kinvolk/inspektor-gadget$ ./kubectl-gadget advise seccomp-profile start -p mariadb     
4IYtOXK53ROoZCrv
francis@pwmachine:~/Codes/kinvolk/inspektor-gadget$ ./kubectl-gadget advise seccomp-profile stop 4IYtOXK53ROoZCrv
{
  "defaultAction": "SCMP_ACT_ERRNO",
  "architectures": [
    "SCMP_ARCH_X86_64",
    "SCMP_ARCH_X86",
    "SCMP_ARCH_X32"
  ],
  "syscalls": [
    {
      "names": [
        "futex"
      ],
      "action": "SCMP_ACT_ALLOW"
    }
  ]
}
```

It fixes #215.

Best regards.

### CODE REVIEW

**Comment by alban** [comment]
With pods containing several containers, it's possible to add a different seccomp profile for each container of the pod. Shouldn't we recommend that instead?

X-Ref: https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.24/#seccompprofile-v1-core
There is a `SeccompProfile` field both in:
* PodSecurityContext (seccomp profile at the pod level)
* SecurityContext (seccomp profile at the container level)

**Comment by blanquicet** [comment]
> > With pods containing several containers, it's possible to add a different seccomp profile for each container of the pod. Shouldn't we recommend that instead?
> 
> This seems to be a good idea! So, instead, trace output would contain as many JSON as containers, right?

Yeah, I think it is a good idea. The problem is how to distinguish which container the seccomp profile belongs to. Maybe we could retry a map where the key is the name of the container and the value is the seccomp profile? I don't see any other field in [the struct](https://pkg.go.dev/github.com/opencontainers/runtime-spec/specs-go#LinuxSeccomp) where we can specify the container name.

**Comment by mauriciovasquezbernal** [comment]
What's the status of this PR? Is there anything we should do to move this forward or should we close it?

**Comment by mauriciovasquezbernal** [comment]
Right, I also agree we can close this. Let's ask @alban since he has more context on this.

**Comment by mauriciovasquezbernal** [comment]
Closing this as we don't want this behavior as stated in https://github.com/inspektor-gadget/inspektor-gadget/issues/215.

**Pull request closed without merging**
