### PR TITLE
RFC: pkg/columns: Use testify

### PR DESCRIPTION
**Pull request by mauriciovasquezbernal**
This library makes the tests more compact and avoids a lot of conditionals.

---

What do you all folks think? IMO we could start using this library in the tests as I think the result tests are more readable.

### CODE REVIEW

**Comment by flyth** [comment]
I agree, it looks much cleaner. I don't think it's worth rewriting all the tests, but if we have to update tests anyways or write new ones, I'll gladly write less but more readable code :)

**Comment by blanquicet** [comment]
Yep, I like it. I checked the repo and I saw a lot of people is using it and even if there hasn't been new releases since Jan 2021, the repo seems to be active enough in case we need something. So, yeah, let's start using it.

**Comment by mauriciovasquezbernal** [comment]
Great, I agree we should not rewrite all tests now, but when updating implementing new ones we should use this library. I added a sentence in the contributing guide to refer to it.

**Review by blanquicet — APPROVED** [review]
LGTM!

**Pull request merged**
