### PR TITLE
[RFE] Added toleration to Inspektor Gadget manifest

### LINKED ISSUE #1885: [RFE] Provide a way to add toleration to Inspektor Gadget manifest
Currently, we install gadget pod with hardcoded [tolerations](https://github.com/inspektor-gadget/inspektor-gadget/blob/v0.18.1/pkg/resources/manifests/deploy.yaml#L281).  This isn't ideal as user may want to install pod at nodes tolerating specific taints. Also, as per [official documentation](https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/):

> There are two special cases:
>    An empty key with operator Exists matches all keys, values and effects which means this will tolerate everything.
 >   An empty effect matches all effects with key key1.

This means the current values should work in most of the cases but still would makes sense to support specifying custom toleration. 

In case of helm charts, we should move the the [hardcoded annoations](https://github.com/inspektor-gadget/inspektor-gadget/blob/v0.18.1/charts/gadget/values.yaml#L38) to template to ensure they are always present (event with `tolerations:
 {}` in values.yaml) so users don't run into any issues.

### PR DESCRIPTION
**Pull request by pawarpranav83**
## Added required toleration field values to Inspektor Gadget manifest

Fixes #1885

Removed hardcoded toleration key values from `values.yaml` file and specified them in`daemonset.yaml`.
Now custom tolerations can be added without overwriting the required tolerations.

## Testing done

Tested with emtpy toleration field in values.yaml, and ran command `make template`.
Also tested with other custom values in toleration field in values.yaml and ran `make template` the output yaml file generated specified the additional fields in proper format.

### CODE REVIEW

**Comment by pawarpranav83** [comment]
cc @mqasimsarfraz

**Comment by mqasimsarfraz** [comment]
Thanks for the contributions :) 

I will trigger a CI run to see everything is green and then test it!

**Review by mqasimsarfraz — APPROVED** [review]
I tested it and it works fine:

```
→ make -C charts build
make: Entering directory '/home/qasim/work/github.com/inspektor-gadget/inspektor-gadget/charts'
rm -rf bin
Building chart:
mkdir -p bin
cp -r gadget bin
cp -r ../pkg/resources/crd/bases bin/gadget/crds
mv bin/gadget/Chart.yaml.tmpl bin/gadget/Chart.yaml
Using GNU sed
sed -i "s/%VERSION%/"1.0.0-dev"/g" bin/gadget/Chart.yaml
sed -i "s/%APP_VERSION%/toleration-change/g" bin/gadget/Chart.yaml
Preparing docs
docker run --user 1000:1000 -v /home/qasim/work/github.com/inspektor-gadget/inspektor-gadget/charts/bin/gadget:/helm-docs jnorwood/helm-docs:v1.11.0 -s file
time="2024-01-25T14:02:03Z" level=info msg="Found Chart directories [.]"
time="2024-01-25T14:02:03Z" level=info msg="Generating README Documentation for chart ."
Charts available at: bin/gadget
make: Leaving directory '/home/qasim/work/github.com/inspektor-gadget/inspektor-gadget/charts'
→ cat bin/values.yaml 
image:
  tag: latest

tolerations:
  - key: CriticalAddonsOnly
    operator: Exists
→ helm upgrade --install gadget charts/bin/gadget/ --namespace gadget --create-namespace -f bin/values.yaml 
Release "gadget" has been upgraded. Happy Helming!
NAME: gadget
LAST DEPLOYED: Thu Jan 25 18:46:19 2024
NAMESPACE: gadget
STATUS: deployed
REVISION: 4
TEST SUITE: None
NOTES:
Inspektor Gadget "toleration-change" installed successfully!

For usage details, visit https://www.inspektor-gadget.io
→ kubectl get pods -n gadget -o yaml | grep -A 10  "tolerations:"
    tolerations:
    - effect: NoSchedule
      operator: Exists
    - effect: NoExecute
      operator: Exists
    - key: CriticalAddonsOnly
      operator: Exists
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
    - effect: NoExecute

```

I will keep it open for a bit to get additional reviews!

**Comment by mqasimsarfraz** [comment]
Thanks for the contribution!

**Pull request merged**
