### PR TITLE
top/ebpf: hide containerImageName column

### PR DESCRIPTION
**Pull request by claudiamarcubina**
# Hide containerImageName column 

- Addresses #1859

Before:
`$ ig top ebpf`

image

After:
`$ ig top ebpf`

image

### CODE REVIEW

**Review by mauriciovasquezbernal — APPROVED** [review]
LGTM from code inspection. Thanks!

**Comment by mauriciovasquezbernal** [comment]
> * Addresses

nit: It's possible to automatically link PRs to close issues when they're merged -> https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword

However, `addresses` is not on the keyword list.

**Review by blanquicet — CHANGES_REQUESTED** [review]
I don't think this is the correct way to fix the issue as such a solution is only addressing the problem for the top ebpf gadget while we want the `ContainerImageName` to not be displayed in any gadget by default, see discussion [here](https://kubernetes.slack.com/archives/CSYL75LF6/p1689687086044749?thread_ts=1689686770.151899&cid=CSYL75LF6).

IMO, the `ContainerImageName` field should be managed as `ContainerID` and `RuntimeName`: 

- Hidden by default using the keyword `hide` in the [column tag](https://github.com/inspektor-gadget/inspektor-gadget/blob/df2743c1bcabbdaf18604e69b454153ab4bfcb18/pkg/types/types.go#L123).
- Manually enabled for the [`list-containers`](https://github.com/inspektor-gadget/inspektor-gadget/blob/df2743c1bcabbdaf18604e69b454153ab4bfcb18/pkg/container-collection/containers.go#L203-L208) and [`list-containers -w`](https://github.com/inspektor-gadget/inspektor-gadget/blob/df2743c1bcabbdaf18604e69b454153ab4bfcb18/cmd/ig/containers/containers.go#L80-L84) commands.

**Comment by claudiamarcubina** [comment]
Moved to #1905 as it is addressing all gadgets, not only top ebpf.

**Pull request closed without merging**
