### PR TITLE
docs: Add tip for trying w/o installation

### PR DESCRIPTION
**Pull request by mqasimsarfraz**
Add a tip for quick-start without installation!

### CODE REVIEW

**Review by alban — APPROVED** [review]
LGTM.

But let's wait a bit to see if there is another opinion.

**Review by mauriciovasquezbernal — COMMENTED** [review]
What about something more generic like:

"Please check the [quick start](https://inspektor-gadget.io/docs/latest/quick-start) guide to learn about the different ways to use Inspektor Gadget"

OR 

add a lot of tabs with all different combinations
gadgetctl 
kubectl node debug
ig on a container

**Comment by mqasimsarfraz** [comment]
> What about something more generic like:
> 
> "Please check the [quick start](https://inspektor-gadget.io/docs/latest/quick-start) guide to learn about the different ways to use Inspektor Gadget"

I fear it might be too generic and it should be fine to show them the quick-start related to kubernetes or linux depending on the tab they select. What do you say?

> OR
> 
> add a lot of tabs with all different combinations gadgetctl kubectl node debug ig on a container

I had a similar idea. But that would mean repeating the guide for each case! :thinking:

**Comment by blanquicet** [comment]
I'm not a big fan of this because, in a Kubernetes environment, users could also copy the `ig` binary into the node and run it from there, use `ig` from a pod, etc. What I mean is that mentioning only those 4 options in the gadgets guide oversimplies the variety of options people have to run Inspektor Gadget. Maybe it's fine for the `Quick Start` just because it's indeed a quick start, but we shouldn't promote those 4 options around the documentation. Probably, we should convert the `Installing on Kubernetes` to `Using on Kubernetes` and explain there all the options I mentioned above, but that's another discussion (out of scope for this PR).

Said that, I'd prefer to show how to run gadgets with `kubectl-gadget` and `ig` in a generic way in the gadgets' documentation, and that's it.

**Comment by blanquicet** [comment]
> One possibility could be to provide the gadget url and then point to the [quick start](https://inspektor-gadget.io/docs/latest/quick-start) in case the users don't have IG available yet. This will be useful for users that start by reading the gadget documentation without first checking the quick-start guide.
>
Could makes sense. Maybe something like "If you’d like to try this gadget but don’t have Inspektor Gadget installed yet, check out the [quick start documentation](https://inspektor-gadget.io/docs/latest/quick-start) for easy setup instructions."

**Pull request closed without merging**
