### PR TITLE
Performances: snapshot socket: use a single bpf iterator

### PR DESCRIPTION
**Pull request by alban**
# snapshot socket: use a single bpf iterator

The snapshot socket gadget was previously using bpf iterators of types iter/udp and iter/tcp. Those bpf iterators need to be executed in each network namespace. This causes bad performance when there are a lot of containers on the node.

This patch uses a bpf iterator of type iter/task_file, iterating on all file descriptors from all processes and skipping the ones that are not tcp or udp sockets.

Benchmarks show performance improvement by 50%:

```
goos: linux
goarch: amd64
pkg: github.com/inspektor-gadget/inspektor-gadget/internal/benchmarks
cpu: Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz
                                                        │  main.bench  │            patched.bench             │
                                                        │    sec/op    │    sec/op     vs base                │
AllGadgetsWithContainers/container100/snapshot-socket-4   516.9m ± 26%   254.4m ± 27%  -50.79% (p=0.000 n=10)
```

The benchmark was produced using the method described in the documentation:
https://github.com/inspektor-gadget/inspektor-gadget/blob/main/docs/devel/CONTRIBUTING.md#benchmarks

Using iter/task_file has the benefit to bring process enrichment (pid, comm, etc).

But it only iterates on sockets that are installed in a process:
1. tcp sockets in TIME_WAIT state are not visible anymore because those are not associated with a struct sock and they do not have an underlying file. See [tcp.h#L442](https://elixir.bootlin.com/linux/v5.15.12/source/include/linux/tcp.h#L442) and [inet_timewait_sock.h#L33](https://elixir.bootlin.com/linux/v5.15.12/source/include/net/inet_timewait_sock.h#L33)
2. server-side tcp sockets that are not accepted yet (the server didn't call the `accept()` system call yet) are no longer visible since they are not a file descriptor (yet).

- [x] Rebased after #1593 got merged in order to reuse the kallsyms package.

## How to use

No changes.

## Testing done

- [x] ig: with tcp sockets using netcat in a Docker container
- [x] ig: udp sockets
- [x] kubectl-gadget
- [x] IPv6

## Issues

Fixes https://github.com/inspektor-gadget/inspektor-gadget/issues/1611
Fixes https://github.com/inspektor-gadget/inspektor-gadget/issues/744

### CODE REVIEW

**Comment by mauriciovasquezbernal** [comment]
> tcp sockets in TIME_WAIT state are not visible anymore because those are not associated with a struct sock and they do not have an underlying file. See [tcp.h#L442](https://elixir.bootlin.com/linux/v5.15.12/source/include/linux/tcp.h#L442) and [inet_timewait_sock.h#L33](https://elixir.bootlin.com/linux/v5.15.12/source/include/net/inet_timewait_sock.h#L33)

Is it really fine not to show sockets on `TIME_WAIT` state? It seems to me that information is useful and not having them will be a shame.

**Comment by alban** [comment]
> Is it really fine not to show sockets on TIME_WAIT state? It seems to me that information is useful and not having them will be a shame.

In that case, using an "iter/task_file" does not work, and we cannot enrich the events with container and process data. I suggest the following solution:
1. Close this PR.
2. Try to implement the snapshot socket with reusing the same instances of ebpf programs. It will help a bit with performance (bpf verifier executed only one time per ebpf program) but we will still have to enter each different network namespace in Go and open/read the iterator each time. It will not have the container and process enrichment.
3. Create a new gadget "snapshot file" using an "iter/task_file", iterating on all open files, including sockets, but not the TIME_WAIT & incoming-but-not-yet-accepted TCP sockets since those don't have a file descriptor. This gadget can also show regular files, and other kinds of files (bpf programs, pipes, etc). It will have container and process enrichment.

In this way, users can have both process enrichment and non-file sockets with good performances but in two different gadgets.

What do you think?

**Comment by alban** [comment]
> Try to implement the snapshot socket with reusing the same instances of ebpf programs

This is already done: https://github.com/inspektor-gadget/inspektor-gadget/pull/1451

But the performances are still not perfect. Example with just 4 containers:

```
$ time sudo ./ig snapshot socket -r docker >/dev/null

real	0m0.882s
user	0m1.186s
sys	0m0.128s
```

I used the bcc profiler on 100 fake containers with the following commands (notice `-s=false` to display userspace stacks correctly):
```
go test -exec sudo -ldflags="-s=false" -bench='^BenchmarkAllGadgetsWithContainers$/^container100$/snapshot-socket' -run=Benchmark ./internal/benchmarks/... -count 100
```

```
sudo /usr/share/bcc/tools/profile -p $(pidof benchmarks.test) --stack-storage-size $((16384*8))
```

Results:

<details>

```
    runtime.greyobject
    runtime.scanobject
    runtime.gcDrain
    runtime.gcBgMarkWorker.func2
    runtime.systemstack.abi0
    runtime.goexit.abi0
    -                benchmarks.test (3452330)
        15

    runtime.findObject
    runtime.scanobject
    runtime.gcDrain
    runtime.gcBgMarkWorker.func2
    runtime.systemstack.abi0
    runtime.goexit.abi0
    -                benchmarks.test (3452330)
        15

    runtime.scanobject
    runtime.gcDrain
    runtime.gcBgMarkWorker.func2
    runtime.systemstack.abi0
    runtime.goexit.abi0
    -                benchmarks.test (3452330)
        17

    runtime.mapaccess1
    github.com/cilium/ebpf/btf.copier.copy
    github.com/cilium/ebpf/btf.copyTypes
    github.com/cilium/ebpf/btf.(*Spec).Copy
    github.com/cilium/ebpf/btf.LoadKernelSpec
    github.com/cilium/ebpf.findTargetInKernel
    github.com/cilium/ebpf.newProgramWithOptions
    github.com/cilium/ebpf.(*collectionLoader).loadProgram
    github.com/cilium/ebpf.(*CollectionSpec).LoadAndAssign.func1
    github.com/cilium/ebpf.assignValues
    github.com/cilium/ebpf.(*CollectionSpec).LoadAndAssign
    github.com/inspektor-gadget/inspektor-gadget/pkg/gadgets/snapshot/socket/tracer.loadIterUDPv4Objects
    github.com/inspektor-gadget/inspektor-gadget/pkg/gadgets/snapshot/socket/tracer.getUDPIter
    github.com/inspektor-gadget/inspektor-gadget/pkg/gadgets/snapshot/socket/tracer.(*Tracer).openIters
    github.com/inspektor-gadget/inspektor-gadget/pkg/gadgets/snapshot/socket/tracer.(*Tracer).Run
    github.com/inspektor-gadget/inspektor-gadget/pkg/runtime/local.(*Runtime).RunGadget
    github.com/inspektor-gadget/inspektor-gadget/internal/benchmarks.BenchmarkAllGadgetsWithContainers.func1.1
    testing.(*B).runN
    testing.(*B).launch
    testing.(*B).doBench.func1
    runtime.goexit.abi0
    -                benchmarks.test (3452330)
        18

    runtime.scanobject
    runtime.gcDrain
    runtime.gcBgMarkWorker.func2
    runtime.systemstack.abi0
    runtime.goexit.abi0
    -                benchmarks.test (3452330)
        18

    runtime.mapassign
    github.com/cilium/ebpf/btf.indexTypes
    github.com/cilium/ebpf/btf.(*Spec).Copy
    github.com/cilium/ebpf/btf.LoadKernelSpec
    github.com/cilium/ebpf.findTargetInKernel
    github.com/cilium/ebpf.newProgramWithOptions
    github.com/cilium/ebpf.(*collectionLoader).loadProgram
    github.com/cilium/ebpf.(*CollectionSpec).LoadAndAssign.func1
    github.com/cilium/ebpf.assignValues
    github.com/cilium/ebpf.(*CollectionSpec).LoadAndAssign
    github.com/inspektor-gadget/inspektor-gadget/pkg/gadgets/snapshot/socket/tracer.loadIterUDPv4Objects
    github.com/inspektor-gadget/inspektor-gadget/pkg/gadgets/snapshot/socket/tracer.getUDPIter
    github.com/inspektor-gadget/inspektor-gadget/pkg/gadgets/snapshot/socket/tracer.(*Tracer).openIters
    github.com/inspektor-gadget/inspektor-gadget/pkg/gadgets/snapshot/socket/tracer.(*Tracer).Run
    github.com/inspektor-gadget/inspektor-gadget/pkg/runtime/local.(*Runtime).RunGadget
    github.com/inspektor-gadget/inspektor-gadget/internal/benchmarks.BenchmarkAllGadgetsWithContainers.func1.1
    testing.(*B).runN
    testing.(*B).launch
    testing.(*B).doBench.func1
    runtime.goexit.abi0
    -                benchmarks.test (3452330)
        18

    runtime.findObject
    runtime.scanobject
    runtime.gcDrain
    runtime.gcBgMarkWorker.func2
    runtime.systemstack.abi0
    runtime.goexit.abi0
    -                benchmarks.test (3452330)
        19

    runtime.mapassign
    github.com/cilium/ebpf/btf.indexTypes
    github.com/cilium/ebpf/btf.(*Spec).Copy
    github.com/cilium/ebpf/btf.LoadKernelSpec
    github.com/cilium/ebpf.findTargetInKernel
    github.com/cilium/ebpf.newProgramWithOptions
    github.com/cilium/ebpf.(*collectionLoader).loadProgram
    github.com/cilium/ebpf.(*CollectionSpec).LoadAndAssign.func1
    github.com/cilium/ebpf.assignValues
    github.com/cilium/ebpf.(*CollectionSpec).LoadAndAssign
    github.com/inspektor-gadget/inspektor-gadget/pkg/gadgets/snapshot/socket/tracer.loadIterTCPv4Objects
    github.com/inspektor-gadget/inspektor-gadget/pkg/gadgets/snapshot/socket/tracer.getTCPIter
    github.com/inspektor-gadget/inspektor-gadget/pkg/gadgets/snapshot/socket/tracer.(*Tracer).openIters
    github.com/inspektor-gadget/inspektor-gadget/pkg/gadgets/snapshot/socket/tracer.(*Tracer).Run
    github.com/inspektor-gadget/inspektor-gadget/pkg/runtime/local.(*Runtime).RunGadget
    github.com/inspektor-gadget/inspektor-gadget/internal/benchmarks.BenchmarkAllGadgetsWithContainers.func1.1
    testing.(*B).runN
    testing.(*B).launch
    testing.(*B).doBench.func1
    runtime.goexit.abi0
    -                benchmarks.test (3452330)
        19

    runtime.mapaccess1
    github.com/cilium/ebpf/btf.copier.copy
    github.com/cilium/ebpf/btf.copyTypes
    github.com/cilium/ebpf/btf.(*Spec).Copy
    github.com/cilium/ebpf/btf.LoadKernelSpec
    github.com/cilium/ebpf.findTargetInKernel
    github.com/cilium/ebpf.newProgramWithOptions
    github.com/cilium/ebpf.(*collectionLoader).loadProgram
    github.com/cilium/ebpf.(*CollectionSpec).LoadAndAssign.func1
    github.com/cilium/ebpf.assignValues
    github.com/cilium/ebpf.(*CollectionSpec).LoadAndAssign
    github.com/inspektor-gadget/inspektor-gadget/pkg/gadgets/snapshot/socket/tracer.loadIterTCPv4Objects
    github.com/inspektor-gadget/inspektor-gadget/pkg/gadgets/snapshot/socket/tracer.getTCPIter
    github.com/inspektor-gadget/inspektor-gadget/pkg/gadgets/snapshot/socket/tracer.(*Tracer).openIters
    github.com/inspektor-gadget/inspektor-gadget/pkg/gadgets/snapshot/socket/tracer.(*Tracer).Run
    github.com/inspektor-gadget/inspektor-gadget/pkg/runtime/local.(*Runtime).RunGadget
    github.com/inspektor-gadget/inspektor-gadget/internal/benchmarks.BenchmarkAllGadgetsWithContainers.func1.1
    testing.(*B).runN
    testing.(*B).launch
    testing.(*B).doBench.func1
    runtime.goexit.abi0
    -                benchmarks.test (3452330)
        20

    b'established_get_first'
    b'established_get_first'
    b'tcp_seek_last_pos'
    b'bpf_iter_tcp_batch'
    b'bpf_iter_tcp_seq_next'
    b'bpf_seq_read'
    b'vfs_read'
    b'ksys_read'
    b'do_syscall_64'
    b'entry_SYSCALL_64_after_hwframe'
    runtime/internal/syscall.Syscall6
    syscall.Syscall
    syscall.read
    internal/poll.(*FD).Read
    os.(*File).Read
    bufio.(*Scanner).Scan
    github.com/inspektor-gadget/inspektor-gadget/pkg/gadgets/snapshot/socket/tracer.(*Tracer).RunCollector.func1
    github.com/inspektor-gadget/inspektor-gadget/pkg/netnsenter.NetnsEnter
    github.com/inspektor-gadget/inspektor-gadget/pkg/gadgets/snapshot/socket/tracer.(*Tracer).RunCollector
    github.com/inspektor-gadget/inspektor-gadget/pkg/gadgets/snapshot/socket/tracer.(*Tracer).Run
    github.com/inspektor-gadget/inspektor-gadget/pkg/runtime/local.(*Runtime).RunGadget
    github.com/inspektor-gadget/inspektor-gadget/internal/benchmarks.BenchmarkAllGadgetsWithContainers.func1.1
    testing.(*B).runN
    testing.(*B).launch
    testing.(*B).doBench.func1
    runtime.goexit.abi0
    -                benchmarks.test (3452330)
        22

    runtime.scanobject
    runtime.gcDrain
    runtime.gcBgMarkWorker.func2
    runtime.systemstack.abi0
    runtime.goexit.abi0
    -                benchmarks.test (3452330)
        28

    runtime.scanobject
    runtime.gcDrain
    runtime.gcBgMarkWorker.func2
    runtime.systemstack.abi0
    runtime.goexit.abi0
    -                benchmarks.test (3452330)
        28

    runtime.findObject
    runtime.scanobject
    runtime.gcDrain
    runtime.gcBgMarkWorker.func2
    runtime.systemstack.abi0
    runtime.goexit.abi0
    -                benchmarks.test (3452330)
        32

    runtime.scanobject
    runtime.gcDrain
    runtime.gcBgMarkWorker.func2
    runtime.systemstack.abi0
    runtime.goexit.abi0
    -                benchmarks.test (3452330)
        34

    runtime.findObject
    runtime.scanobject
    runtime.gcDrain
    runtime.gcBgMarkWorker.func2
    runtime.systemstack.abi0
    runtime.goexit.abi0
    -                benchmarks.test (3452330)
        34

    runtime.greyobject
    runtime.scanobject
    runtime.gcDrain
    runtime.gcBgMarkWorker.func2
    runtime.systemstack.abi0
    runtime.goexit.abi0
    -                benchmarks.test (3452330)
        34

    runtime.greyobject
    runtime.scanobject
    runtime.gcDrain
    runtime.gcBgMarkWorker.func2
    runtime.systemstack.abi0
    runtime.goexit.abi0
    -                benchmarks.test (3452330)
        48

    runtime.scanobject
    runtime.gcDrain
    runtime.gcBgMarkWorker.func2
    runtime.systemstack.abi0
    runtime.goexit.abi0
    -                benchmarks.test (3452330)
        60

    runtime.findObject
    runtime.scanobject
    runtime.gcDrain
    runtime.gcBgMarkWorker.func2
    runtime.systemstack.abi0
    runtime.goexit.abi0
    -                benchmarks.test (3452330)
        61

WARNING: 2 stack traces could not be displayed. Consider increasing --stack-storage-size.
```

</details>

Most of the time is spent in the Golang garbage collector. The bpf program execution (stack with `bpf_iter_tcp_seq_next`) or the bpf program initialization (stack with `newProgramWithOptions`) does not take the majority of the time.

**Comment by alban** [comment]
Using pprof to see what's using the most cpu/memory:

```
go test \
    -cpuprofile cpu.prof -memprofile mem.prof \
    -exec sudo \
    -ldflags="-s=false" \
    -bench='^BenchmarkAllGadgetsWithContainers$/^container100$/snapshot-socket' \
    -run=Benchmark ./internal/benchmarks/... \
    -count 5
```

```
$ go tool pprof -top cpu.prof 
File: benchmarks.test
Build ID: a560a22371c1fc40f6c4be3c5535a8c104f04ecf
Type: cpu
Time: May 15, 2023 at 12:49pm (CEST)
Duration: 8.82s, Total samples = 13.72s (155.59%)
Showing nodes accounting for 12.34s, 89.94% of 13.72s total
Dropped 185 nodes (cum <= 0.07s)
      flat  flat%   sum%        cum   cum%
     1.92s 13.99% 13.99%      5.56s 40.52%  runtime.scanobject
     1.34s  9.77% 23.76%      1.79s 13.05%  runtime.findObject
     0.68s  4.96% 28.72%      1.12s  8.16%  runtime.mapaccess1
     0.57s  4.15% 32.87%      2.05s 14.94%  runtime.mapassign
     0.56s  4.08% 36.95%      0.68s  4.96%  runtime.heapBitsSetType
     0.55s  4.01% 40.96%      0.57s  4.15%  runtime.pageIndexOf (inline)
     0.54s  3.94% 44.90%      0.54s  3.94%  runtime/internal/syscall.Syscall6
     0.48s  3.50% 48.40%      0.48s  3.50%  runtime.memclrNoHeapPointers
     0.46s  3.35% 51.75%      2.32s 16.91%  runtime.mallocgc
     0.44s  3.21% 54.96%      0.44s  3.21%  runtime.heapBits.bits (inline)
     0.39s  2.84% 57.80%      0.39s  2.84%  runtime.markBits.isMarked (inline)
     0.36s  2.62% 60.42%      1.38s 10.06%  runtime.greyobject
     0.34s  2.48% 62.90%      0.34s  2.48%  runtime.memmove
     0.25s  1.82% 64.72%      0.31s  2.26%  runtime.mapassign_faststr
     0.23s  1.68% 66.40%      0.27s  1.97%  runtime.spanOf (inline)
     0.21s  1.53% 67.93%      0.21s  1.53%  runtime.heapBitsForAddr (inline)
     0.20s  1.46% 69.39%      0.63s  4.59%  runtime.evacuate
     0.17s  1.24% 70.63%      0.88s  6.41%  github.com/cilium/ebpf/btf.walkType
```

```
$ go tool pprof -top mem.prof 
File: benchmarks.test
Build ID: a560a22371c1fc40f6c4be3c5535a8c104f04ecf
Type: alloc_space
Time: May 15, 2023 at 12:49pm (CEST)
Showing nodes accounting for 2647.99MB, 96.35% of 2748.44MB total
Dropped 167 nodes (cum <= 13.74MB)
      flat  flat%   sum%        cum   cum%
 1153.78MB 41.98% 41.98%  2165.03MB 78.77%  github.com/cilium/ebpf/btf.copier.copy
  406.55MB 14.79% 56.77%   406.55MB 14.79%  github.com/cilium/ebpf/btf.copyMembers (inline)
  390.21MB 14.20% 70.97%   390.21MB 14.20%  github.com/cilium/ebpf/btf.indexTypes
  214.36MB  7.80% 78.77%   214.36MB  7.80%  github.com/cilium/ebpf/internal.(*Deque[...]).Grow
  187.52MB  6.82% 85.59%   187.52MB  6.82%  github.com/cilium/ebpf/btf.(*FuncProto).copy
   74.50MB  2.71% 88.30%    74.50MB  2.71%  github.com/cilium/ebpf/btf.(*Func).copy
   60.50MB  2.20% 90.50%   448.55MB 16.32%  github.com/cilium/ebpf/btf.(*Struct).copy
   55.90MB  2.03% 92.54%  1159.90MB 42.20%  github.com/cilium/ebpf/btf.copyTypes
   22.01MB   0.8% 93.34%    22.01MB   0.8%  github.com/cilium/ebpf/btf.(*Enum).copy
      21MB  0.76% 94.10%       21MB  0.76%  github.com/cilium/ebpf/btf.(*Pointer).copy
   16.03MB  0.58% 94.69%    31.74MB  1.15%  github.com/cilium/ebpf/btf.inflateRawTypes
   13.08MB  0.48% 95.16%    14.16MB  0.52%  github.com/cilium/ebpf/btf.inflateRawTypes.func3
   13.03MB  0.47% 95.63%    23.53MB  0.86%  github.com/cilium/ebpf/btf.readTypes
    8.52MB  0.31% 95.94%    14.52MB  0.53%  github.com/cilium/ebpf/btf.readStringTable
    7.50MB  0.27% 96.22%    26.01MB  0.95%  github.com/cilium/ebpf/btf.(*Union).copy
       2MB 0.073% 96.29%    22.68MB  0.83%  github.com/cilium/ebpf/btf.(*encoder).deflateType
    0.50MB 0.018% 96.31%  2676.68MB 97.39%  github.com/cilium/ebpf.newProgramWithOptions
    0.50MB 0.018% 96.33%  1061.52MB 38.62%  github.com/cilium/ebpf/btf.coreCalculateFixups
    0.50MB 0.018% 96.35%  1106.62MB 40.26%  github.com/cilium/ebpf.applyRelocations
```

**Pull request closed without merging**
