### PR TITLE
trace/exec: Fix reading task->loginuid in kernels without CONFIG_AUDIT

### PR DESCRIPTION
**Pull request by mauriciovasquezbernal**
Use bpf_core_field_exists() to only read this value when it's available.

Fixes https://github.com/inspektor-gadget/inspektor-gadget/issues/1769

@alban do you have an environment ready to test it out?

### CODE REVIEW

**Comment by alban** [comment]
> @alban do you have an environment ready to test it out?

Yes, I will test it.

**Comment by alban** [comment]
It still fails:

```
        ; event->timestamp = bpf_ktime_get_boot_ns();
        76: (85) call bpf_ktime_get_boot_ns#125
        77: (79) r1 = *(u64 *)(r10 -40)
        ; event->gid = gid;
        78: (63) *(u32 *)(r1 +28) = r6
         R0_w=inv(id=0) R1_w=map_value(id=0,off=0,ks=4,vs=7752,imm=0) R6_w=inv(id=0,umax_value=4294967295,var_off=(0x0; 0xffffffff)) R7_w=inv(id=0,umax_value=4294967295,var_off=(0x0; 0xffffffff)) R8=inv(id=1) R9=inv(id=2) R10=fp0 fp-8=inv fp-16=mmmm???? fp-24=mmmmmmmm fp-32=inv fp-40_w=map_value fp-48_w=ctx
        ; event->uid = uid;
        79: (63) *(u32 *)(r1 +24) = r8
         R0_w=inv(id=0) R1_w=map_value(id=0,off=0,ks=4,vs=7752,imm=0) R6_w=inv(id=0,umax_value=4294967295,var_off=(0x0; 0xffffffff)) R7_w=inv(id=0,umax_value=4294967295,var_off=(0x0; 0xffffffff)) R8=inv(id=1) R9=inv(id=2) R10=fp0 fp-8=inv fp-16=mmmm???? fp-24=mmmmmmmm fp-32=inv fp-40_w=map_value fp-48_w=ctx
        ; event->pid = tgid;
        80: (63) *(u32 *)(r1 +16) = r7
         R0_w=inv(id=0) R1_w=map_value(id=0,off=0,ks=4,vs=7752,imm=0) R6_w=inv(id=0,umax_value=4294967295,var_off=(0x0; 0xffffffff)) R7_w=inv(id=0,umax_value=4294967295,var_off=(0x0; 0xffffffff)) R8=inv(id=1) R9=inv(id=2) R10=fp0 fp-8=inv fp-16=mmmm???? fp-24=mmmmmmmm fp-32=inv fp-40_w=map_value fp-48_w=ctx
        ; event->timestamp = bpf_ktime_get_boot_ns();
        81: (7b) *(u64 *)(r1 +8) = r0
         R0_w=inv(id=0) R1_w=map_value(id=0,off=0,ks=4,vs=7752,imm=0) R6_w=inv(id=0,umax_value=4294967295,var_off=(0x0; 0xffffffff)) R7_w=inv(id=0,umax_value=4294967295,var_off=(0x0; 0xffffffff)) R8=inv(id=1) R9=inv(id=2) R10=fp0 fp-8=inv fp-16=mmmm???? fp-24=mmmmmmmm fp-32=inv fp-40_w=map_value fp-48_w=ctx
        82: (18) r1 = 0xffffffff
        84: (b7) r2 = 0
        ; if (bpf_core_field_exists(task->loginuid))
        85: (15) if r2 == 0x0 goto pc+8
        last_idx 85 first_idx 85
         R0_w=inv(id=0) R1_w=inv4294967295 R2_rw=invP0 R6_w=inv(id=0,umax_value=4294967295,var_off=(0x0; 0xffffffff)) R7_w=inv(id=0,umax_value=4294967295,var_off=(0x0; 0xffffffff)) R8=inv(id=1) R9=inv(id=2) R10=fp0 fp-8=inv fp-16=mmmm???? fp-24=mmmmmmmm fp-32=inv fp-40_w=map_value fp-48_w=ctx
        parent didn't have regs=4 stack=0 marks
        last_idx 84 first_idx 70
        regs=4 stack=0 before 84: (b7) r2 = 0
        ; event->loginuid = BPF_CORE_READ(task, loginuid.val);
        94: (79) r7 = *(u64 *)(r10 -40)
        ; event->loginuid = 4294967295; // -1 or "no user id"
        95: (63) *(u32 *)(r7 +32) = r1
         R0=inv(id=0) R1=inv4294967295 R2=invP0 R6=inv(id=0,umax_value=4294967295,var_off=(0x0; 0xffffffff)) R7_w=map_value(id=0,off=0,ks=4,vs=7752,imm=0) R8=inv(id=1) R9=inv(id=2) R10=fp0 fp-8=inv fp-16=mmmm???? fp-24=mmmmmmmm fp-32=inv fp-40=map_value fp-48=ctx
        96: (85) call unknown#195896080
        invalid func unknown#195896080
        processed 76 insns (limit 1000000) max_states_per_insn 0 total_states 6 peak_states 6 mark_read 5
DEBU[0001] calling operator.PostGadgetRun()
DEBU[0001] calling RemoveMountNsMap()
DEBU[0001] calling Unsubscribe()
Error: running gadget: running gadget: installing tracer: loading ebpf spec: loading maps and programs: field IgExecveE: program ig_execve_e: load program: invalid argument: invalid func unknown#195896080 (136 line(s) omitted)
```

Now I see that `sessionid` is also missing on WSL2:
On Fedora:
```
$ sudo bpftool btf dump id 1 format c
...
struct task_struct {
...
        struct callback_head *task_works;
        struct audit_context *audit_context;
        kuid_t loginuid;
        unsigned int sessionid;
        struct seccomp seccomp;
```
On WSL2:
```
$ sudo bpftool btf dump file ./vmlinux-WSL2 format c
...
struct task_struct {
...
        struct callback_head *task_works;
        struct seccomp seccomp;
```

**Comment by mauriciovasquezbernal** [comment]
@alban update it to also check if sessionid is available. Would you mind testing again?

**Comment by alban** [comment]
> @alban update it to also check if sessionid is available. Would you mind testing again?

It works now!

**Comment by mauriciovasquezbernal** [comment]
> Maybe we can do something with `__kconfig CONFIG_AUDIT`, but I am afraid `cilium/ebpf` will explode if this is `not set`.

In these cases it's better to use `bpf_core_field_exists` to avoid relying on the different `CONFIG_`.

**Comment by mauriciovasquezbernal** [comment]
> It works now!

Thanks for testing it.

**Pull request merged**
