### PR TITLE
refactoring: port uprobe support

### PR DESCRIPTION
**Pull request by flyth**
This commit from @mauriciovasquezbernal ports basic uprobe support to the new architecture / eBPF operator.

### CODE REVIEW

**Comment by alban** [comment]
@i-Pear Could you review this PR? Thanks!

**Comment by i-Pear** [comment]
Looks good to me, thanks. The code here is identical to #2580.

**Comment by i-Pear** [comment]
By the way, what's the difference between `pkg/gadgets/run` and `pkg/operators/ebpf`? Is the latter meant for use on k8s?
And for future uprobe features, do I need to implement changes in both places?

**Comment by flyth** [comment]
> Looks good to me, thanks. The code here is identical to #2580.

I'd change authorship to you in that case - or do you want to open a PR yourself?

> By the way, what's the difference between pkg/gadgets/run and pkg/operators/ebpf? Is the latter meant for use on k8s?
And for future uprobe features, do I need to implement changes in both places?

With #2512, we just merged an overhaul of the architecture regarding image based gadgets (`pkg/operators/ebpf` etc.) - the run gadget `pkg/gadgets/run` will be removed soon. So if possible, please try to migrate the code to the new operator and feel free to ask questions around it and let me know if you need any help.

**Comment by i-Pear** [comment]
> the run gadget pkg/gadgets/run will be removed soon. So if possible, please try to migrate the code to the new operator
Thanks, I understand, will soon rebase my next PR onto `pkg/operators/ebpf`.

In my next PR, most code here will be removed, and a new package `uprobetracer` will be introduced. So I think maybe we can just close this PR, and I will rebase the new logic into `pkg/operators/ebpf`? @alban Wdyt?

**Review by alban — APPROVED** [review]

**Comment by alban** [comment]
@flyth feel free to merge if the CI does not reveal any problems.

**Pull request merged**
