### PR TITLE
New gadget: tracepkt

### PR DESCRIPTION
**Pull request by alban**
# New gadget: tracepkt

The tracepkt gadget installs a TRACE iptables rule in the raw table to mark packets that come from a specific pod. This causes iptables to log each matching iptables rule for that packet. The kernel log is not easily parsable in syslog and it misses metadata (network namespace id, interface indexes...) so this gadget uses a kprobe on the nf_log_trace function to catch the log and add missing information. The TRACE rule only log iptables rules that, once evaluated, matches the packet, but it is possible to infer the iptables rules that are evaluated but don't match the packet, so the gadget also fetches those iptables rules and display the logical sequence for the user.

Two TRACE rules are installed:
* In the raw table, OUTPUT chain, in the pod network namespace. This marks the packet from the time it is sent. This allows to log iptables rules installed in the pod network namespaces, if any (this is unusual but some privileged containers can install iptables rules).
* In the raw table, PREROUTING chain, in the host network namespace. This marks the packet as soon as it enters the host network namespace after being sent from the container. This allows to log iptables rules installed in the host network namespace by Calico. To filter on the container, the gadget identifies the veth for the container on the host netns side.

The TRACE iptables rules have a comment identifying the Trace CR that initiated them.

The kubectl-gadget CLI can display rules with indentation to help visualise how the chains are calling each other. Each displayed rule has a comment:
- `[rule]`: the rule was evaluated and it matched the packet
- `[skip]`: the rule was evaluated and it didn't match the packet
- `[return]`: the user-defined chain completed its evaluation and the parent chain will continue the evaluation
- `[policy]`: the built-in chain completed its evaluation and has a default policy ACCEPT or DROP

## How to use

Deploy some workload and network policies:
```
kubectl apply -f docs/examples/tracepkt/01-workload.yaml
calicoctl apply -f docs/examples/tracepkt/02-network-policy.yaml
```

Start the tracepkt gadget on the workload:
```
kubectl gadget tracepkt --namespace tracepkt-demo --podname hello
```

Send some network packets:
```
kubectl exec -ti -n tracepkt-demo hello -- wget -O /dev/null https://1.1.1.1
```

image

## Testing done

- [x] Egress traffic

## TODO

- [ ] Complete documentation & guide
- [x] Ingress traffic
- [ ] Egress traffic (possibly need to install additional TRACE iptables rules)
- [ ] Remove TRACE rules when the gadget tracepkt is stopped
- [ ] Performance: don't fork/exec `iptables -L` for each packet: keep a short-lived cache
- [ ] Use Netnsenter from https://github.com/kinvolk/inspektor-gadget/pull/428

## References

Supersedes https://github.com/kinvolk/inspektor-gadget/pull/36
Related: https://github.com/projectcalico/felix/pull/3088

### CODE REVIEW

**Comment by marga-kinvolk** [comment]
Amazing :). Is it possible to check the performance impact of this change?

**Comment by alban** [comment]
> Is it possible to check the performance impact of this change?

For now it is quite bad because it executes "iptables -L" (via the coreos/go-iptables package) for each rule that a packet matches. We don't get the full rules from eBPF. I'd like to implement a cache so that the same "iptables -L" command is not executed more than 1 time per second.

The gadget installs a a TRACE iptables rule on a specific network interface, so only the traffic from that pod is impacted. It also only matches TCP SYN packets.

**Comment by alban** [comment]
This seems to do something similar: https://github.com/rafaeldtinoco/conntracker. Comparison:
* It uses kprobes on tcp_connect, udp_send_skb, etc. instead of kprobe on nf_log_trace.
* It uses `iptables -j TRACE` as well ([link](https://github.com/rafaeldtinoco/conntracker/blob/649dc70a35d4e9af34f961babee129b1019a3e6e/iptables.c#L144)).
* It uses netlink to get the log ([link](https://github.com/rafaeldtinoco/conntracker/blob/649dc70a35d4e9af34f961babee129b1019a3e6e/nlmsg.c#L118)) instead of ebpf kprobe on nf_log_trace

**Comment by alban** [comment]
Moving the code to an external gadget:
https://github.com/alban/iptables-gadget

The rest can be tracked in an external issue:
https://github.com/alban/iptables-gadget/issues/1

**Pull request closed without merging**
