### PR TITLE
go.mod: update cilium/ebpf

### PR DESCRIPTION
**Pull request by alban**
This includes the changes that have been merged upstream:
https://github.com/cilium/ebpf/pull/920

This should improve the performances of loading bpf modules.

This PR removes the temporary performance workaround introduced in the SocketEnricher (https://github.com/inspektor-gadget/inspektor-gadget/pull/1201) since it is now done by cilium/ebpf directly.

Note: deprecated tags in generated files are removed, see: https://github.com/cilium/ebpf/pull/888

### CODE REVIEW

**Comment by alban** [comment]
This PR introduces the following CI failure:
```
=== CONT  TestEventEnrichmentRaceCondition
time="2023-02-15T17:19:47Z" level=warning msg="WithTracerCollection: failed to open mntns reference for container 16eb1f83-7f7c-47fb-86e0-b9ae9bc0106c: too many open files"
    gadgets_test.go:247: failed generating events: failed to run command: running command: open /dev/null: too many open files
--- FAIL: TestEventEnrichmentRaceCondition (2.50s)
=== CONT  TestContainerRemovalRaceCondition
    gadgets_test.go:176: failed generating events: failed to run command: running command: open /dev/null: too many open files
--- FAIL: TestContainerRemovalRaceCondition (2.60s)
```

But I don't know how it is related.

The tests pass fine on my computer.

**Review by mauriciovasquezbernal — APPROVED** [review]
I think those are flaky tests and are not related to this PR for sure. I just kicked the CI again and then I'll open an issue to fix those tests. 

I think we can merge this PR once tests pass.

**Comment by mauriciovasquezbernal** [comment]
Forget my previous message. The tests are not flaky and are always failing. I can reproduce it on my computer with `$ go test -exec sudo -test.v ./...`.  I'll investigate further.

**Comment by mauriciovasquezbernal** [comment]
@alban would you mind rebasing on top of https://github.com/inspektor-gadget/inspektor-gadget/pull/1330? I think that will fix the issue.

**Comment by alban** [comment]
> @alban would you mind rebasing on top of https://github.com/inspektor-gadget/inspektor-gadget/pull/1330? I think that will fix the issue.

Done

**Comment by alban** [comment]
It seems to bring other issues:

> Gadget tcpconnect: falling back to standard tracer. CO-RE tracer failed: failed to load ebpf program: field IgTcpcV4CoE: program ig_tcpc_v4_co_e: map .rodata: load BTF: load btf: invalid argument: [1] DATASEC .rodata size=280 vlen=7: type_id=5 offset=272 size=8 Invalid type (45 line(s) omitted)
>
> $ go run -exec sudo -tags withebpf ./cmd/local-gadget/... traceloop -r docker
>
> Error: error creating tracer: loading ebpf program: field IgTraceloopE: program ig_traceloop_e: map .rodata: load BTF: load btf: invalid argument: [1] DATASEC .rodata size=264 vlen=9: type_id=5 offset=96 size=168 Invalid type (62 line(s) omitted)

The diff in cilium/ebpf:
> git log ea299d354cf6..a478cd839367

Could be related to https://github.com/cilium/ebpf/issues/921?

**Comment by alban** [comment]
I updated this PR so that it cherry-picks this PR:
      collection: work around excessive copying of kernel BTF
      https://github.com/cilium/ebpf/pull/920

But without taking all upstream changes due to:
      btf: vmlinux .data..percu Datasec is refused by the kernel
      https://github.com/cilium/ebpf/issues/921

**Comment by mauriciovasquezbernal** [comment]
Great! Still LGTM, feel free to merge.

**Pull request merged**
