### PR TITLE
gadgets/top_file: Provide full file path

### PR DESCRIPTION
**Pull request by MeherRushi**
# gadgets/top_file: Provide full file path

- Modified the File parameter in `top_file` gadget to show the absolute file path
## How to use

run top_file gadget, and create a pod and put some data into a file 
Just followed steps as mentioned in the [documentation](https://inspektor-gadget.io/docs/latest/gadgets/top_file)

## Testing done

- Before modifying the code, I ran the `top_file` gadget:
```bash
sudo -E ig run top_file:latest --containername test-top-file
```
> this would capture all the events running on the container with name test-top-file.

- Then I opened another terminal and ran the following commands to create a container named test-top-file and exec into it:
```bash
docker run --rm --name test-top-file -it ubuntu /bin/sh
```
- Then in the container, I ran the following command 
```bash
echo trail > /foo.txt & echo trail > /home/foo.txt
```
- and got the following output from the `top_file` gadget trace:
Screenshot from 2024-08-13 18-53-11

- After modifying the code, I rebuilt the gadget locally using :
```bash
sudo -E ig image build -t top_file:v1 .
```
- After that I ran the locally built gadget using :
```bash
sudo -E ig run top_file:v1 --public-keys=''  --containername test-top-file
```

- Then I re-ran the command in the test container:
```bash
echo trail > /foo.txt & echo trail > /home/foo.txt
```
- and got the following output from the `top_file` gadget trace after modification
Screenshot from 2024-08-13 19-21-23

### CODE REVIEW

**Review by mauriciovasquezbernal — COMMENTED** [review]
This looks very good. Please update the following as well:

- docs: gadgets/top_file/README.mdx
- tests: gadgets/top_file/test/top_file_test.go


Also, please improve the commit message title to be something like:
`gadgets/top_file: Provide full file path` and then include some more information in the commit message body if needed.

**Comment by MeherRushi** [comment]
@mauriciovasquezbernal Thanks for the review. 
Will make the required changes soon

**Comment by mauriciovasquezbernal** [comment]
@MeherRushi I see you pushed few days ago, but I can't see any changes on that. Did you forgot to add some files?

**Comment by MeherRushi** [comment]
@mauriciovasquezbernal , Yes there seems to be an issue trying to run gadgets using kubectl gadget on my end. I had tested it for the ig tool and it works.

I did ask for help on the slack channel @Francis Laniel is helping me out with it.

Really sorry for the delay of the PR. Will update it soon

**Comment by mauriciovasquezbernal** [comment]
> Really sorry for the delay of the PR. Will update it soon

Nothing to worry about, I was just checking the status of it. Thanks for the update.

**Comment by MeherRushi** [comment]
Hey @mauriciovasquezbernal , I have updated the docs and tests for the same. Please review it once.

**Comment by mauriciovasquezbernal** [comment]
The linter is failing. Could you please run `make clang-format` and push the updated file?

**Review by mauriciovasquezbernal — APPROVED** [review]
LGTM. I'll merge once the CI is green.

**Pull request merged**
