### PR TITLE
Introduce initial version of CODEOWNERS

### PR DESCRIPTION
**Pull request by mauriciovasquezbernal**
@blanquicet @blixtra @eiffel-fl @burak-ok @claudiamarcubina @flyth @mqasimsarfraz please feel free to suggest areas you're interested in being code owners.

### CODE REVIEW

**Comment by flyth** [comment]
I wouldn't mind taking/sharing these:

```
/cmd/common/registry.go @flyth
/pkg/columns/ @flyth
/pkg/gadget-context/ @flyth
/pkg/gadget-registry/ @flyth
/pkg/gadget-service/ @flyth
/pkg/params/ @flyth
/pkg/operators/operators.go @flyth
/pkg/runtime/ @flyth
```

**Comment by mqasimsarfraz** [comment]
I would like to suggest myself for:

```
/.github/ @mqasimsarfraz
/Dockerfiles/ @mqasimsarfraz 
/charts/ @mqasimsarfraz 
/integration/ @mqasimsarfraz 
/pkg/container-collection/ @mqasimsarfraz 
/pkg/container-utils/ @mqasimsarfraz 
/tools/ @mqasimsarfraz 
```

**Comment by burak-ok** [comment]
```
/pkg/container-utils/containerd/ @burak-ok
/pkg/operators/kubeipresolver/ @burak-ok
/pkg/operators/kubenameresolver/ @burak-ok
/pkg/gadgets/run/ @burak-ok
```

Not so sure about scope, ...
```
/integration/ @burak-ok
/gadgets/ @burak-ok
```

**Comment by mauriciovasquezbernal** [comment]
> Not so sure about scope, ...
>
> /integration/ @burak-ok
/gadgets/ @burak-ok

I'm not sure I follow. What do you mean?

**Comment by burak-ok** [comment]
> > Not so sure about scope, ...
> > /integration/ @burak-ok
> > /gadgets/ @burak-ok
> 
> I'm not sure I follow. What do you mean?

I am not sure if I should be a codeowner for the whole `integration` subdirectory or not.
Or the `gadgets` subdirectory

**Comment by blanquicet** [comment]
I'm interested in these:

```
cmd/ig/
integration/
pkg/container-collection/ 
pkg/container-utils/ 
pkg/gadgets/internal/networktracer/
pkg/gadgets/profile/tcprtt/
pkg/gadgets/snapshot/socket/
pkg/gadgets/trace/dns
pkg/gadgets/trace/network
pkg/gadgets/trace/sni
pkg/histogram/
pkg/ig-manager/
pkg/types/
```

Please let me know if you think I missed something I could take 🙂.

**Comment by mauriciovasquezbernal** [comment]
> I am not sure if I should be a codeowner for the whole `integration` subdirectory or not.
> Or the `gadgets` subdirectory

It's totally up to you. For integration we already have @blanquicet and @mqasimsarfraz, for the whole gadgets sub-directory I didn't put anybody. (that'd default to me and Alban). Perhaps it's better if there is any specific gadget you want to own.

**Comment by mauriciovasquezbernal** [comment]
ok folks, thanks a lot. I think we have a very good "coverage" for the first iteration. Please somebody review and approve.

Also, remember that this list is dynamic, we can add and remove owners later on.

**Review by alban — APPROVED** [review]

**Pull request merged**
