### PR TITLE
metadata: Clean up parameters handling

### PR DESCRIPTION
**Pull request by mauriciovasquezbernal**
- Move eBPF parameters under parameters leaf
- Remove `GadgetParams`

Initially developed as part of #3449

### Release notes

The gadget metadata (gadget.yaml) changed its format: ebpfParams was moved to params.ebpf. As a consequence, the parameters of gadgets compiled with ig <= v0.32.0 are not parsed in ig >= v0.33.0. To avoid any issues, run matching versions of ig and gadgets.

### CODE REVIEW

**Review by burak-ok — APPROVED** [review]
LGTM, thanks

**Comment by alban** [comment]
The changes looks good, but it will break compatibility:
- Gadgets compiled with ig <= v0.32.0 will no longer work with ig > v0.33.0 or latest because of the change in gadget.yaml
- Third-party software using the IG Golang API (and gRPC clients & servers using inconsistent versions): pkg/operators/ebpf/params.go has some compatibility layer to support parameters with prefixes "ebpfParams." and "params.ebpf." but not prefix "params.". For consistency, we should support the 3 forms or just the most recent form, but it seems weird to keep compatibility with the oldest and newest forms.

Could we add a "release note" section in the PR description about it? Then the next release notes should include it. We could have a label in the PR to indicate it contains release notes.

**Comment by mauriciovasquezbernal** [comment]
I know the compatibility on this one is weird. d28c76d0ef853f40fa5594b24e3febf044b757d6 added support for `ebpfParams` and `params` but the Gadgets weren't updated to use `params` and the metadata generation continued to use `ebpfParams`. I don't think there are gadgets using `params`, that's why I didn't added support for that one but kept the `ebpfParams` one.

Btw, it's possible to use official gadgets compiled with a previous version of Inspektor Gadget after this PR:

```bash 
$ sudo ig run trace_open:v0.32.0

# works fine
```

I still can add a release note, but I'm not sure what to put there.

**Comment by alban** [comment]
> Btw, it's possible to use official gadgets compiled with a previous version of Inspektor Gadget after this PR:

But does the CLI parameter work?
```
sudo ig run trace_open:v0.32.0 --help
sudo ig run trace_open:v0.32.0 --uid=1000
```

> I still can add a release note, but I'm not sure what to put there.

Something like: The gadget metadata (`gadget.yaml`) changed its format: `ebpfParams` was moved to `params.ebpf`. As a consequence, the parameters of gadgets compiled with ig <= v0.32.0 are not parsed in ig >= v0.33.0. To avoid any issues, run matching versions of ig and gadgets.

**Comment by mauriciovasquezbernal** [comment]
> But does the CLI parameter work?

Yes, it does:

```bash 
$ sudo ig run trace_open:v0.32.0 --uid 1001 --host
WARN[0000] Ignoring runtime "cri-o" with non-existent socketPath "/run/crio/crio.sock"
WARN[0000] Ignoring runtime "podman" with non-existent socketPath "/run/podman/podman.sock"
RUNTIME.CONTAINERNAME      COMM                  PID        TID        UID        GID  FD FNAME                    MODE           ERROR
                           DNS Res~ver #…       4243      56894       1001       1001 136 /etc/hosts               ----------
                           tmux: server        30546      30546       1001       1001  10 /proc/60377/cmdline      ----------
                           gnome-shell          3593       3593       1001       1001 154 /proc/self/stat          ----------
                           DNS Res~er #1…       4243      56905       1001       1001 136 /etc/hosts               ----------
                           BgIOThr~ool #…       4243      59912       1001       1001 136 /home/mauriciov/snap/fi… -rw-rw-rw-
                           Cache2 I/O           4243       4411       1001       1001 136 /home/mauriciov/snap/fi… -rw-------
                           Cache2 I/O           4243       4411       1001       1001 202 /proc/self/mountinfo     ----------
                           Cache2 I/O           4243       4411       1001       1001 202 /proc/self/mountinfo     ----------
                           dbus-daemon          3446       3446       1001       1001  80 /sys/kernel/security/ap… ----------
                           cpptools            48333      48349       1001       1001  55 /proc/56577/status       -rw-rw-rw-
                           cpptools            48333      48349       1001       1001  55 /proc/54916/status       -rw-rw-rw-
                           cpptools            48333      48349       1001       1001  55 /proc/55569/status       -rw-rw-rw-
                           cpptools            48333      48349       1001       1001  55 /proc/53858/status       -rw-rw-rw-
                           tmux: server        30546      30546       1001       1001  10 /proc/60377/cmdline      ----------
                           tmux: server        30546      30546       1001       1001  10 /proc/60377/cmdline      ----------
                           tmux: server        30546      30546       1001       1001  10 /proc/60377/cmdline      ----------
```

**Pull request merged**
