### PR TITLE
Dockerfiles: Upgrade packages on BASE_IMAGE.

### PR DESCRIPTION
**Pull request by eiffel-fl**
This avoids releasing an image with CVE.

### CODE REVIEW

**Comment by mqasimsarfraz** [comment]
It will definitely help avoid CVEs in the base image. The only tricky bit I would like to understand is how [docker cache](https://github.com/inspektor-gadget/inspektor-gadget/blob/main/.github/workflows/inspektor-gadget.yml#L337) in the CI will behave. Essentially everything people experienced here: https://github.com/moby/moby/issues/3313.

**Comment by mqasimsarfraz** [comment]
> I do not think we can have fresh (i.e. patched) and cache at the same time.

Agreed. I am not sure how much time are we getting out of cache anyways. Probably not a lot!

**Review by mqasimsarfraz — APPROVED** [review]
LGTM! Thanks for handling feedback. Please wait for another review before merge.

**Review by mauriciovasquezbernal — COMMENTED** [review]
I'm not sure why it's something we should take care of. Shouldn't it be done by the base image publisher?

**Pull request closed without merging**
