### PR TITLE
integration: Tests for SnapshotUDPSocket #3235

### PR DESCRIPTION
**Pull request by btwshivam**
# Added Missing tests for gadgets/snapshot_socket #3235

added unit Test for SnapshotUDPSocket

### CODE REVIEW

**Comment by btwshivam** [comment]
hey @mauriciovasquezbernal I have added tests for UDP socket. what more can I implement or add?

**Comment by mauriciovasquezbernal** [comment]
Hi @btwshivam. The idea of https://github.com/inspektor-gadget/inspektor-gadget/issues/3235 is to port the tests on https://github.com/inspektor-gadget/inspektor-gadget/blob/main/integration/k8s/snapshot_socket_test.go to gadgets/snapshot_socket. Something like https://github.com/inspektor-gadget/inspektor-gadget/commit/42d58fe2c804a5e2e0d21b81e779d38b24c4aebb, but for the snapshot_socket gadget. I you can add the new test you implemented here (for UDP) there as well.

**Comment by btwshivam** [comment]
> Hi @btwshivam. The idea of #3235 is to port the tests on https://github.com/inspektor-gadget/inspektor-gadget/blob/main/integration/k8s/snapshot_socket_test.go to gadgets/snapshot_socket. Something like [42d58fe](https://github.com/inspektor-gadget/inspektor-gadget/commit/42d58fe2c804a5e2e0d21b81e779d38b24c4aebb), but for the snapshot_socket gadget. You can add the new test you implemented here (for UDP) there as well.

okay got that thanks!

**Comment by mastersans** [comment]
Hi @btwshivam you can also take reference from this documentation: https://www.inspektor-gadget.io/blog/2024/06/introducing-the-new-testing-framework-for-image-based-gadgets/

**Comment by btwshivam** [comment]
closing this PR and opening another with proper format.

**Pull request closed without merging**
