### PR TITLE
pkg/datasource: Use FullName to look for fields in config

### PR DESCRIPTION
**Pull request by blanquicet**
# Use FullName to look for fields in config

Similar to https://github.com/inspektor-gadget/inspektor-gadget/pull/3293 and https://github.com/inspektor-gadget/inspektor-gadget/pull/3271, we are not using the `FullName` to look for fields. This prevents us from correctly annotating fields.

## Testing done

Try to annotate fields with parent like this:

```bash
diff --git a/gadgets/top_tcp/gadget.yaml b/gadgets/top_tcp/gadget.yaml
index d942a1aa51c6..dcd89c74c7bd 100644
--- a/gadgets/top_tcp/gadget.yaml
+++ b/gadgets/top_tcp/gadget.yaml
@@ -8,6 +8,9 @@ datasources:
     annotations:
       cli.clear-screen-before: "true"
     fields:
+      runtime.containername:
+        annotations:
+          columns.hidden: true
       mntns_id:
         annotations:
           description: Mount namespace inode id
```

Then, build and push the gadget:

```bash
$ go run ./cmd/ig/... image build -t $LOCAL_REPO/top_tcp:no-run-container gadgets/top_tcp/
Pulling builder image ghcr.io/inspektor-gadget/ebpf-builder:latest
latest: Pulling from inspektor-gadget/ebpf-builder
Digest: sha256:993dd2ee641faaf7a038df4534c893023a0a94edd24b9ba127c2eb70a00ea33a
Status: Image is up to date for ghcr.io/inspektor-gadget/ebpf-builder:latest
Successfully built ghcr.io/blanquicet/top_tcp:no-run-container@sha256:ac0e605d9600f9220249b91dec3f314fa087923b5c6302d9b6a401d2d105dbf7
```

```bash
$ go run ./cmd/ig/... image push $LOCAL_REPO/top_tcp:no-run-container
Pushing ghcr.io/blanquicet/top_tcp:no-run-container...
Successfully pushed ghcr.io/blanquicet/top_tcp:no-run-container@sha256:ac0e605d9600f9220249b91dec3f314fa087923b5c6302d9b6a401d2d105dbf7
```

Then, run the same gadget with and without this PR:

- **Before this PR:** Annotation is not applied:

```bash
$ go run --exec "sudo -E" ./cmd/ig/... run $LOCAL_REPO/top_tcp:no-run-container --verify-image=false
RUNTIME.CONTAINERNAME         PID SRC                         DST                         COMM        SENT       RECEIVED
RUNTIME.CONTAINERNAME         PID SRC                         DST                         COMM        SENT       RECEIVED
RUNTIME.CONTAINERNAME         PID SRC                         DST                         COMM        SENT       RECEIVED
```

- **After this PR:** Annotation is applied:

```bash
go run --exec "sudo -E" ./cmd/ig/... run $LOCAL_REPO/top_tcp:no-run-container --verify-image=false
       PID SRC                                DST                                COMM           SENT          RECEIVED
```

### CODE REVIEW

**Comment by flyth** [comment]
Hmm, I think it's fine this way, although we had a different structure before (when we still defined structs and not datasources), afair, e.g.

```yaml
fields:
  fieldA:
    fields:
      fieldB:
        annotations:
...
```

instead of

```yaml
fields:
  fieldA.fieldB:
    annotations:
...
```

for `fieldA.fieldB`. But now that we reduced the amount of things we define in here, I think it's totally okay.

/cc @mauriciovasquezbernal WDYT?

**Comment by mauriciovasquezbernal** [comment]
I'm not sure what the question is. If you are asking if it's ok to define a field by using the dot notation

```
fields:
  fieldA.fieldB:
    annotations:
...
```

instead of creating the tree

```
fields:
  fieldA:
    fields:
      fieldB:
        annotations:
...
```

that seems good to me. If you're asking something else please let me know.

**Comment by flyth** [comment]
> I'm not sure what the question is. If you are asking if it's ok to define a field by using the dot notation
> 
> 
> 
> ```
> 
> fields:
> 
>   fieldA.fieldB:
> 
>     annotations:
> 
> ...
> 
> ```
> 
> 
> 
> instead of creating the tree
> 
> 
> 
> ```
> 
> fields:
> 
>   fieldA:
> 
>     fields:
> 
>       fieldB:
> 
>         annotations:
> 
> ...
> 
> ```
> 
> 
> 
> that seems good to me. If you're asking something else please let me know.

Yeah i was asking exactly that :)

**Review by flyth — APPROVED** [review]
LGTM. Please just fix the typo in the commit msg/pkg.

**Comment by blanquicet** [comment]
Merged as test failing is not related with this PR

**Pull request merged**
