### PR TITLE
socketenricher: Fix cleaning up the sockets map

### PR DESCRIPTION
**Pull request by mauriciovasquezbernal**
Fixes https://github.com/inspektor-gadget/inspektor-gadget/pull/1201

### CODE REVIEW

**Review by alban — APPROVED** [review]

**Review by alban — CHANGES_REQUESTED** [review]
The code looks good but I can reproduce the bug on my laptop (5.18.9-200.fc36.x86_64). I am investigating...

**Comment by mauriciovasquezbernal** [comment]
I quickly checked it, something like this fixes the tests but we should look for a correct way to clean it up:

```diff
$ git diff
diff --git pkg/gadgets/internal/socketenricher/tracer_test.go pkg/gadgets/internal/socketenricher/tracer_test.go
index e8bfbba8..0db1b7a5 100644
--- pkg/gadgets/internal/socketenricher/tracer_test.go
+++ pkg/gadgets/internal/socketenricher/tracer_test.go
@@ -224,7 +224,7 @@ func bindSocketWithOpts(ipStr string, domain, typ int, port int, opts []sockOpt)
        if err != nil {
                return 0, err
        }
-       defer unix.Close(fd)
+       //defer unix.Close(fd)
 
        for _, opt := range opts {
                if err := unix.SetsockoptInt(fd, opt.level, opt.opt, opt.value); err != nil {
```

**Comment by alban** [comment]
I fixed the tests in #1312.

**Comment by mauriciovasquezbernal** [comment]
Will be handled in https://github.com/inspektor-gadget/inspektor-gadget/pull/1312.

**Pull request closed without merging**
