### PR TITLE
discussion on approaches to implement event-generator

### PR DESCRIPTION
**Pull request by h4l0gen**
# Discussion on approaches to implement event-generation utility

## Testing done
Yes

### CODE REVIEW

**Comment by h4l0gen** [comment]
- flag approach: dns event-generator output
```bash
h4logen@kapil:~/new-ig-arch/inspektor-gadget$ go run --exec "sudo -E" ./cmd/ig run trace_dns --filter name==example.com. --eventgen-enable=true --eventgen-type=dns --eventgen-target=example.com
INFO[0000] Experimental features enabled                
WARN[0000] Ignoring runtime "cri-o" with non-existent socketPath "/run/crio/crio.sock" 
RUNTIME.CONTAINERNAME          SRC                                     DST                                     COMM                   PID QR QTYPE           NAME                          RCODE    ADDRESSES      
WARN[0014] Replacement map "gadget_sockets" incompatible: ValueSize: 8272 changed to 64: map spec is incompatible with existing map 
WARN[0014] Is trace_dns compatible with ig 0.0.0?       
INFO[0014] Starting EventGen with type: dns, target: example.com 
minikube                       10.244.0.62:48145                       10.96.0.10:53                                                    0 Q  A               example.com.                                          
minikube                       10.244.0.62:48145                       10.244.0.26:53                                                   0 Q  A               example.com.                                          
DNS lookup output:
Performing DNS lookup for example.com
Server:		10.96.0.10
Address:	10.96.0.10:53

Non-authoritative answer:
Name:	example.com
Address: 93.184.215.14

Non-authoritative answer:
Name:	example.com
Address: 2606:2800:21f:cb07:6820:80da:af6b:8b2c

DNS lookup completed

INFO[0019] Generated dns event using pod dns-test-pod-1727700258 
INFO[0019] Starting EventGen with type: dns, target: example.com 
minikube                       10.244.0.62:48145                       10.96.0.10:53                                                    0 Q  AAAA            example.com.                                          
minikube                       10.244.0.62:48145                       10.244.0.26:53                                                   0 Q  AAAA            example.com.                                          
minikube                       10.244.0.26:40171                       192.168.49.1:53                                                  0 Q  AAAA            example.com.                                          
minikube                       10.244.0.26:48557                       192.168.49.1:53                                                  0 Q  A               example.com.                                          
minikube                       192.168.49.1:53                         10.244.0.26:48557                                                0 R  A               example.com.                  Success  93.184.215.14  
minikube                       192.168.49.1:53                         10.244.0.26:48557                                                0 R  A               example.com.                  Success  93.184.215.14  
minikube                       192.168.49.1:53                         10.244.0.26:40171                                                0 R  AAAA            example.com.                  Success  2606:2800:21f:…
minikube                       192.168.49.1:53                         10.244.0.26:40171                                                0 R  AAAA            example.com.                  Success  2606:2800:21f:…
minikube                       10.244.0.26:53                          10.244.0.62:48145                                                0 R  A               example.com.                  Success  93.184.215.14  
minikube                       10.96.0.10:53                           10.244.0.62:48145                                                0 R  A               example.com.                  Success  93.184.215.14  
minikube                       10.244.0.26:53                          10.244.0.62:48145                                                0 R  AAAA            example.com.                  Success  2606:2800:21f:…
minikube                       10.96.0.10:53                           10.244.0.62:48145                                                0 R  AAAA            example.com.                  Success  2606:2800:21f:…
minikube                       10.244.0.63:60827                       10.96.0.10:53                                                    0 Q  A               example.com.                                          
minikube                       10.244.0.63:60827                       10.244.0.26:53                                                   0 Q  A               example.com.                                          
minikube                       10.244.0.63:60827                       10.96.0.10:53                                                    0 Q  AAAA            example.com.                                          
DNS lookup output:
Performing DNS lookup for example.com
Server:		10.96.0.10
Address:	10.96.0.10:53

Name:	example.com
Address: 93.184.215.14

Name:	example.com
Address: 2606:2800:21f:cb07:6820:80da:af6b:8b2c

DNS lookup completed

INFO[0023] Generated dns event using pod dns-test-pod-1727700263 
minikube                       10.244.0.63:60827                       10.244.0.26:53                                                   0 Q  AAAA            example.com.                                          
minikube                       10.244.0.26:53                          10.244.0.63:60827                                                0 R  A               example.com.                  Success  93.184.215.14  
minikube                       10.96.0.10:53                           10.244.0.63:60827                                                0 R  A               example.com.                  Success  93.184.215.14  
minikube                       10.244.0.26:53                          10.244.0.63:60827                                                0 R  AAAA            example.com.                  Success  2606:2800:21f:…
minikube                       10.96.0.10:53                           10.244.0.63:60827                                                0 R  AAAA            example.com.                  Success  2606:2800:21f:…
^CSuccessfully deleted pod dns-test-pod-1727700263 in namespace default
INFO[0041] Cleaned up event pod dns-test-pod-1727700263 
Successfully deleted pod dns-test-pod-1727700258 in namespace default
INFO[0041] Cleaned up event pod dns-test-pod-1727700258`
```


I still need  to polish this output, but this is overall how it will work.

**Comment by h4l0gen** [comment]
Hi folks, I am Kapil Sharma, working on [event-generation](https://github.com/inspektor-gadget/inspektor-gadget/issues/3193) with [@Burak Ok](https://kubernetes.slack.com/team/U042GTWLDH8) and [@Qasim Sarfraz](https://kubernetes.slack.com/team/U01S39E4D3J). I have came up with two approaches to implement event-generation within Inspektor-gadget. These are the most promising approaches I found (please feel free to suggest any other approach you may have):
- Flag approach: using eventgen as a flag that can be used while running gadgets. For example, using the DNS event generator:

`$ go run --exec "sudo -E" ./cmd/ig run trace_open --eventgen-enable=true --eventgen-type=dns --eventgen-target=example.com`

Its a concise approach simply can run event-generator along with gadgets. Here we can run gadget and enable event-generator, so event-generator will create events and gadget will show that. I have included the complete output of this approach in a [draft PR](https://github.com/inspektor-gadget/inspektor-gadget/pull/3538#issuecomment-2389136897), please take a look.

- Sub-command Approach: I have previously implemented this with the July version (with kubectl-gadget).

using eventgen  as a Sub-command allows it to run separately from the gadget, meaning both processes are independent and don't rely on each other.
we can run gadget like this

`$ ./kubectl-gadget trace dns`

In another terminal, we can run the DNS event generator to generate events:

`$ ./kubectl-gadget eventgen dns example.com`

The gadget will catch and display events generated by the DNS event generator.I would like your suggestions on which approach would be more suitable.I have created a [draft PR](https://github.com/inspektor-gadget/inspektor-gadget/pull/3538) for the first approach to start discussion. Thank you!

**Comment by blanquicet** [comment]
Thanks for creating this space to discuss. I have some comments already.

Regarding flags vs sub-command:

- I like this feature being implemented as flags because it allows to synchronize the event generation with the gadget lifecycle, i.e., start generating events only after the gadget was actually started and (in a follow-up PR) validate output once gadget is stopped. I'm a little bit worry about the number of flags, but after merging [#3515](https://github.com/inspektor-gadget/inspektor-gadget/pull/3515), users will be able to change this:

    ```bash
    ig run trace_dns --filter name==example.com. --eventgen-enable=true --eventgen-type=dns --eventgen-target=example.com
    ```

  into this:

    ```yaml
    version: 1
    kind: instance-spec
    imageName: trace_dns
    name: capture_dns_events
    paramValues:
      operator.filter.filter: "name==example.com."
      operator.eventgen.eventgen-enable: true
      operator.eventgen.eventgen-type: dns
      operator.eventgen.eventgen-target: example.com
    ``` 

- On the other side, I like the idea of sub-command because it allows to use one single event generation for more than one gadget. For instance, HTTPS events with trace_dns, trace_tcpconnect, or downloading/uploading test files with trace_tcpdrop, trace_tcpretrans. However, we will lost the ability to sync with gadget lifecycle.
- In the end, I think I prefer the flag implementation.

Regarding operator implementation:

- The generation of events must happen on server side.
- The environment where events will be generated shouldn't be tight to Kubernetes (probably what you did was just an example). I suggest re-using the [Container interface](https://github.com/inspektor-gadget/inspektor-gadget/blob/main/pkg/container-utils/testutils/container_interface.go#L39) we created for testing. With few changes, it'll allow us to run commands on docker/containerd containers (even though in this case we don't care about the runtime), but also in Kubernetes containers by keeping a common interface. In addition, we can extend it to allow creating container with specific linux namespaces. For instance, to create container with the host network linux namespace for generating DNS or HTTPS events for `ig` running as standalone with the `--host` flag.

In general, I think we can start by providing a subset of eventgen-type: dns and https. But at a certain point, as we did for gadgets, we should allow people running custom things like bash scripts or even WASM. Let's keep it in the back of our mind.

**Comment by mqasimsarfraz** [comment]
> The generation of events must happen on server side.

This is a great discussion point. One of the main concerns with server side generation would mean to allow `gadget` pod (via RBAC) to be able to `create/delete` pods in all the namespace which I am not sure we should be doing. Having said that we do need server side generation for existing pods/containers (switching to particular namespace and generating events from there) so would be nice if we can find a way to do it in the same way for both. One idea to avoid touching RBAC permission would be to skip talking to API server for pods but rather use CRI API in Kubernetes and Container Runtime APIs for runtimes using [Container interface](https://github.com/inspektor-gadget/inspektor-gadget/blob/main/pkg/container-utils/testutils/container_interface.go#L39) like you mentioned. Any thoughts on this?

**Comment by blanquicet** [comment]
> > The generation of events must happen on server side.
> 
> This is a great discussion point. One of the main concerns with server side generation would mean to allow `gadget` pod (via RBAC) to be able to `create/delete` pods in all the namespace which I am not sure we should be doing. Having said that we do need server side generation for existing pods/containers (switching to particular namespace and generating events from there) so would be nice if we can find a way to do it in the same way for both. One idea to avoid touching RBAC permission would be to skip talking to API server for pods but rather use CRI API in Kubernetes and Container Runtime APIs for runtimes using [Container interface](https://github.com/inspektor-gadget/inspektor-gadget/blob/main/pkg/container-utils/testutils/container_interface.go#L39) like you mentioned. Any thoughts on this?
>

Oh, raised a great point. Yeah, I would avoid modifying the RBAC for the ig-k8s pod. So, at this point, we will need to differentiate the implementation:
- ig and ig+gadgetctl: On server side
- kubectl-gadget: On client side

WDYT?

**Comment by blanquicet** [comment]
> Having said that we do need server side generation for existing pods/containers (switching to particular namespace and generating events from there)
> 
Why do we need this?

**Comment by mqasimsarfraz** [comment]
> > Having said that we do need server side generation for existing pods/containers (switching to particular namespace and generating events from there)
> 
> Why do we need this?

Imagine if you want to troubleshoot DNS for existing pod, in this case it would be helper if we can generate the request from the given pod and see it works fine. Does that make sense?

**Comment by burak-ok** [comment]
> On the other side, I like the idea of sub-command because it allows to use one single event generation for more than one gadget. For instance, HTTPS events with trace_dns, trace_tcpconnect, or downloading/uploading test files with trace_tcpdrop, trace_tcpretrans. However, we will lost the ability to sync with gadget lifecycle.

I think that there would be no problem to implement such features for the flag approach too. The event-gen should not be directly tied to the gadget.
So soemthing like `kubectl gadget eventgen http` or `kubectl gadget run trace_tcp --eventgen http` should be equivalent

The only problem we might have (with both approaches) comes when we want to verify the gadget output. The verification is gadget specific, but not the event generation

**Comment by blanquicet** [comment]
> > On the other side, I like the idea of sub-command because it allows to use one single event generation for more than one gadget. For instance, HTTPS events with trace_dns, trace_tcpconnect, or downloading/uploading test files with trace_tcpdrop, trace_tcpretrans. However, we will lost the ability to sync with gadget lifecycle.
> 
> I think that there would be no problem to implement such features for the flag approach too. The event-gen should not be directly tied to the gadget. 
> 
If it's an operator, by default, it's tied to the gadget's lifecycle, i.e., it'll start generating events when gadget starts and stop doing it when gadget stops. In fact, the `eventgen-enable` would be an instance parameter, so users can only ask to start generating events when running a given gadget. How to do that if you have more than one?

> So soemthing like `kubectl gadget eventgen http` or `kubectl gadget run trace_tcp --eventgen http` should be equivalent
> 
If I didn't miss anything on my above comment, they are not.

> The only problem we might have (with both approaches) comes when we want to verify the gadget output. The verification is gadget specific, but not the event generation. (Of course generating file events for network gadgets makes no sense, etc..)
>
Nope, for same reason I described above. If `eventgen-enable`, `eventgen-type`, etc., are instance parameters, each eventgen operator instance is associated to a specific gadget, so the verification.

**Comment by burak-ok** [comment]
I thought you meant using (for example) an http event generator for different gadgets in different instances.

Did you mean starting the event generator and then in parallel use multiple gadgets to capture the events?

**Comment by blanquicet** [comment]
> I thought you meant using (for example) an http event generator for different gadgets in different instances.
> 
> Did you mean starting the event generator and then in parallel use multiple gadgets to capture the events?
>
Yes. For instance, one may want to know if a host is able to reach a specific endpoint and with what latency. So, they'd generate HTTP events and then run, in parallel, `trace_dns` and `trace_tcpconnect` (both specs defined in a [manifest file](https://github.com/inspektor-gadget/inspektor-gadget/pull/3485)) to know:

- Whether the URL was resolved or not and, in case, the error
- Whether the TCP connection got established or not and, in case, the error
- The TCP and DNS latency

**Comment by burak-ok** [comment]
> That's why I concluded saying it prefer the flag implementation, at least we will have a perfect synchronization for one single gadget.

(Thinking out loud). Maybe we could control with a flag how many gadgets should run before the event gen actually starts generating. Our operator framework allows for that. But it gets complicated and in the way of other things maybe

**Comment by blanquicet** [comment]
> > That's why I concluded saying it prefer the flag implementation, at least we will have a perfect synchronization for one single gadget.
> 
> (Thinking out loud). Maybe we could control with a flag how many gadgets should run before the event gen actually starts generating. Our operator framework allows for that. But it gets complicated and in the way of other things maybe
>
I think it'd imply "synchronization" between operator's instances, which doesn't exist right now. I don't know how complex it would be. However, let's keep it in mind. I suggest adding it to future implements:

> let's track all the improvements we are planning in https://github.com/inspektor-gadget/inspektor-gadget/issues/3193:
>
> - The eventgen operator could also validate gadget output and disable normal gadget output. It could just say, "all the generated events were captured" or "X was missing" (and print the gadget output).
> - Allow generating events on existing pods/containers.
>
- Support using one single event generator for more than one gadget running in parallel and capturing the events. An example of use case is described [here](https://github.com/inspektor-gadget/inspektor-gadget/pull/3538#issuecomment-2394183007).

**Comment by blanquicet** [comment]
To summarize, I think we kind of agreed on the following initial proposal:

- Event generator is associated to one single gadget using operator's parameters, i.e., CLI flags or `paramValues` in [manifest file](https://github.com/inspektor-gadget/inspektor-gadget/pull/3515)).
- Events are generated on server side, except for Kubernetes.
- Events are generated on pods/containers created by the event generator itself and not on existing pods/containers (For now).
- Event generator doesn't validate output (For now).

What do you all think?

**Comment by mqasimsarfraz** [comment]
> To summarize, I think we kind of agreed on the following initial proposal:
> 
> * Event generator is associated to one single gadget using operator's parameters, i.e., CLI flags or `paramValues` in [manifest file](https://github.com/inspektor-gadget/inspektor-gadget/pull/3515).
> * Events are generated on server side, except for Kubernetes.
> * Events are generated on pods/containers created by the event generator itself and not on existing pods/containers (For now).
> * Event generator doesn't validate output (For now).
> 
> What do you all think?

+1, sounds good to me. If we all agree I will update https://github.com/inspektor-gadget/inspektor-gadget/issues/3193 for future improvements!

**Comment by blanquicet** [comment]
@h4l0gen what do you think?

**Comment by h4l0gen** [comment]
Hi, I have been following entire discussion, I also liked the synchronization idea so +1 from my side to flag approach. Just two concerns/doubts I have in my mind:
> Events are generated on server side

`server side` concept still not much clear to me, It would be great help if you guys can guide me in this. 

secondly, How we are planning about validation, are we going to compare output with expected output. Something like [this](https://github.com/inspektor-gadget/inspektor-gadget/blob/main/gadgets/trace_dns/test/trace_dns_test.go#L134).

**Pull request closed without merging**
